apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-quxf-rc
spec:
  replicas: 1
  selector:
    app: mysql-quxf
  template:
    metadata:
      labels:
        app: mysql-quxf
    spec:
      volumes:
      - name: mysql-data
        hostPath:
          path: /data/data/mysql
      - name: mysql-etc
        hostPath:
          path: /code/docker/my.cnf
      containers:
      - name: mysql
        image:  percona:5.7.25
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
          - name: mysql-etc
            mountPath: /etc/mysql/conf.d/out.cnf
    
