apiVersion: v1
kind: ReplicationController
metadata:
  name: test-mysql
spec:
  replicas: 1
  selector:
    app: test-mysql
  template:
    metadata:
      labels:
        app: test-mysql
    spec:
      containers:
      - name: test-mysql
        image: percona:5.7.25
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
