apiVersion: v1
kind: Pod
metadata:
  name: dbs
  labels:
    name: dbs
spec:
  containers:
  - name: percona1
    image: percona:5.7.22
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "123456"

  - name: redis1
    image: redis:alpine
